name: Deploy personal website (Hugo)

on:
  push:
    branches:
      - main
      - feat/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.119.0'
        extended: true

    - name: Build
      run: hugo --minify
    
    