name: Deploy personal website (Hugo)

on:
  push:
    branches:
      - main
      - feat/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: personal-website
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.119.0'
        extended: true

    - name: Build
      run: hugo --minify
    
    - name: Sync files to root location
      env:
        FTP_HOST: ${{ vars.PERSONAL_WEB_FTP_URL }}
        FTP_USERNAME: ${{ secrets.PERSONAL_WEB_FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.PERSONAL_WEB_FTP_PASSWORD }}
      run: |
        RSYNC_RSH="sshpass -p $FTP_PASSWORD ssh -o StrictHostKeyChecking=no" \
        rsync -avz --delete -e "$RSYNC_RSH" ./public/ $FTP_USERNAME@$FTP_HOST:/public_html/
